### ISSUE TITLE
Verify contracts

### ISSUE THREAD

**Issue by brunowowk** [0xSplits/splits-contracts#7]
Is there any reason why deployed splits are not verified on Etherscan/Sourcify?

**Comment by wminshew** [comment]
yes we use a custom [clone library](https://github.com/0xSplits/splits-contracts/blob/main/contracts/libraries/Clones.sol). You can verify them on etherscan after they've received 1 txn I believe. Less familiar w sourcify

`SplitMain` itself is verified (which includes the dependencies such as the clone library etc)

**Comment by brunowowk** [comment]
Oh, so there's no actual code to verify, since it's just the minimal bytecode. Got it.

So, the reason Etherscan does not recognize it as a proxy (before the first txn) is because that is a minimal proxy that does not conform to EIP-1167? Was there any reason to use that instead of the EIP one, besides the [200 gas saved on deploy and 4 gas on calls](https://medium.com/coinmonks/the-more-minimal-proxy-5756ae08ee48#:~:text=200%20less%20gas%20to%20deploy%20(one%20fewer%20byte%20of%20runtime%20code)%20and%204%20less%20gas%20to%20call)?

If that is the case, did you folks try reaching out to Etherscan to work out that limitation? It seems like a big deal for general adoption.

**Comment by wminshew** [comment]
> Was there any reason to use that instead of the EIP one .. ?

the gas savings on deploy/call weren't the focus; the focus was full compatibility w solidity `send`/`transfer`. The EIP minimal proxy will trigger a `delegatecall` on every call which will cause the gas-capped `send`/`transfer` to fail. Splits were designed to work seamlessly with any calling contract, regardless of the gas cap used to xfr funds

> If that is the case, did you folks try reaching out to Etherscan to work out that limitation?

we worked w them for a bit and ended up at the "splits are verified after 1 txn" solution. Maybe you'll have better luck reaching out. So far to the best of our knowledge it hasn't impeded adoption since `SplitMain` is verified & that's really all devs have needed

**Comment by brunowowk** [comment]
@wminshew thanks for taking the time to explain 🫡

**Comment by wminshew** [comment]
> @wminshew thanks for taking the time to explain 🫡

🫡
